### PR TITLE
removed debian distro instructions on installing redis, removed auto-…

### PR DESCRIPTION
**Pull request by DanielSeehausen**
…generated file, removed .lock and updated .gitignore

### CODE REVIEW

**Comment by sgharms** [comment]
@DanielSeehausen 

Around this section:

> To see it in action, you'll first need to start Redis: `redis-server` (on OS X you can also follow the instructions that `brew info redis` prints to start Redis automatically using launchctl.) Then run your Rails server (don't forget to restart) in one tab, and open a new Terminal tab to run Sidekiq with this command:

Could we add some side-by-side screenshots. What you're describing here is a very professional way of orienting terms to get data back about two daemon processes...but I think online only students would really benefit from "seeing" a desktop like a pro would use.

**Comment by sgharms** [comment]
Other than that, I'd say it's done.

**Comment by DanielSeehausen** [comment]
Image added -- please review @sgharms

**Comment by sgharms** [comment]
:shipit:

**Pull request merged**
